const STATUS_CODE = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
};

const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",
  INPUT_ERROR: "INPUT_ERROR",
  INVALID_STATE_ERROR: "INVALID_STATE_ERROR",
  SERVER_ERROR: "SERVER_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
  FILESYSTEM_ERROR: "FILESYSTEM_ERROR",
  NETWORK_ERROR: "NETWORK_ERROR",
  QUEUE_ERROR: "QUEUE_ERROR",
  EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
  CUSTOMER_ERROR: "CUSTOMER_ERROR",
};

const TYPE = [1, 2, 3, 4, 5]

module.exports = {
    STATUS_CODE,
    ERROR_CODES,
    TYPE,
}